import { registerDropProcessing01 } from './cases/drop-processing-01.ts';
import { registerDropProcessing02 } from './cases/drop-processing-02.ts';
import { registerDropProcessing03 } from './cases/drop-processing-03.ts';
import { registerDropProcessing04 } from './cases/drop-processing-04.ts';
import { registerDropProcessing05 } from './cases/drop-processing-05.ts';
import { registerDropProcessing06 } from './cases/drop-processing-06.ts';
import { registerDropProcessing07 } from './cases/drop-processing-07.ts';
import { registerDropProcessing08 } from './cases/drop-processing-08.ts';
import { registerDropProcessing09 } from './cases/drop-processing-09.ts';
import { registerDropProcessing10 } from './cases/drop-processing-10.ts';
import { registerDropProcessing11 } from './cases/drop-processing-11.ts';
import { registerDropProcessing12 } from './cases/drop-processing-12.ts';
import { registerDropProcessing13 } from './cases/drop-processing-13.ts';
import { registerDropProcessing14 } from './cases/drop-processing-14.ts';
import { registerDropProcessing15 } from './cases/drop-processing-15.ts';
import { registerDropProcessing16 } from './cases/drop-processing-16.ts';
import { registerDropProcessing17 } from './cases/drop-processing-17.ts';
import { registerDropProcessing18 } from './cases/drop-processing-18.ts';
import { registerDropProcessing19 } from './cases/drop-processing-19.ts';
import { registerDropProcessing20 } from './cases/drop-processing-20.ts';
import { registerDropProcessing21 } from './cases/drop-processing-21.ts';
import { registerDropProcessing22 } from './cases/drop-processing-22.ts';

registerDropProcessing01();
registerDropProcessing02();
registerDropProcessing03();
registerDropProcessing04();
registerDropProcessing05();
registerDropProcessing06();
registerDropProcessing07();
registerDropProcessing08();
registerDropProcessing09();
registerDropProcessing10();
registerDropProcessing11();
registerDropProcessing12();
registerDropProcessing13();
registerDropProcessing14();
registerDropProcessing15();
registerDropProcessing16();
registerDropProcessing17();
registerDropProcessing18();
registerDropProcessing19();
registerDropProcessing20();
registerDropProcessing21();
registerDropProcessing22();
