import type { AppState, TwitchDrop, TwitchGame } from '../types/index.ts';
import type { UnverifiableRewardMarker } from './runtime-timing-state.ts';
import type { TwitchSession } from './twitch-api/types.ts';

export interface ServiceWorkerState {
  appState: AppState;
  backupImportInProgress: boolean;
  backupImportCompletion: Promise<void> | null;
  backupImportRequested: boolean;
  runtimeHandlersInFlight: number;
  optionalPermissionRevisions: { notificationsEnabled: number; telegramAlertsEnabled: number };
  monitorTickInFlight: boolean;
  cancelledAcquisitionMonitoringWake: (() => boolean) | null;
  monitorTickDeadlineAt: number;
  streamerAcquisitionInFlight: Promise<boolean> | null;
  queueProgressionInFlight: {
    readonly epoch: number;
    readonly generation: number;
    readonly promise: Promise<boolean>;
  } | null;
  streamerAcquisitionDeadlineAt: number;
  streamerAcquisitionGeneration: number;
  streamerAcquisitionPhase: 'directory' | 'playback' | null;
  preparingManagedTabIds: Set<number>;
  tickGeneration: number;
  invalidStreamChecks: number;
  lastStreamRotationAt: number;
  streamValidationGraceUntil: number;
  lastTrackedProgress: number;
  lastTrackedMinutes: number;
  lastTrackedDropKey: string | null;
  lastProgressAdvanceAt: number;
  noProgressRotationAttempts: number;
  offlineChecks: number;
  avoidStreamerName: string | null;
  gamesCacheRefreshInFlight: Promise<TwitchGame[]> | null;
  twitchSessionCache: TwitchSession | null;
  twitchSessionFetchInFlight: Promise<TwitchSession | null> | null;
  twitchSessionLastAttemptAt: number;
  cachedDropsSnapshot: TwitchDrop[];
  previousAllDropsCount: number;
  cachedCampaignChannelsMap: Record<string, string[] | null>;
  lastFullRefreshAt: number;
  lastInventoryRefreshAt: number;
  dropClaimInFlight: boolean;
  dropClaimRetryAtById: Map<string, number>;
  lastActivityAt: number;
  apiConsecutiveFailures: number;
  apiBackoffUntil: number;
  apiRetryAfterVerifiedAt?: number;
  integrityFallbackActive: boolean;
  integrityFallbackActiveUntil: number;
  recoveryBackoffUntil: number;
  lastRecoveryAttemptAt: number;
  stalledRecoveryAttempts: number;
  lastHeartbeatAt: number;
  lastLifecycleCheckAt: number;
  lastGamesCacheRefreshAt: number;
  hasCurrentGenerationCampaignValidation: boolean;
  unverifiableRewardsByKey: Record<string, UnverifiableRewardMarker>;
}
